---
# Template configuration files for openshift-install

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ openshift-install_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - openshift-install_enable_selinux
  become: true
